//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 11:35:40 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.jaxws.ws.example.nhan/")
package ws.wsdl;
